version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
